# Generated by Django 4.1.5 on 2023-08-24 02:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_auth', '0002_rename_username_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friend_of', to='user_auth.student'),
        ),
        migrations.AddField(
            model_name='student',
            name='friendship_requests',
            field=models.ManyToManyField(blank=True, related_name='requested_by', to='user_auth.student'),
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
