# Generated by Django 4.1.5 on 2023-08-24 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_student_following_student_friends_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
