# Generated by Django 4.2.1 on 2023-09-05 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0014_alter_student_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.RemoveField(
            model_name='student',
            name='username',
        ),
    ]
