# Generated by Django 4.1.7 on 2023-09-07 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPost', '0007_alter_post_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_posted', 'author']},
        ),
    ]
