# Generated by Django 4.1.7 on 2023-09-07 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPost', '0008_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_posted', '-author']},
        ),
    ]
