# Generated by Django 4.1.7 on 2023-09-07 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPost', '0009_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_posted']},
        ),
    ]
